In [2]:
from datetime import date, datetime
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import psycopg2
import seaborn as sns
from sqlalchemy import create_engine

import finPal_pandascan

pandascan = finPal_pandascan.pandascan()

datetime.strftime(datetime.today(), '%Y-%m-%d')

'2021-08-09'

In [3]:
dbTable = 'gd_wTi_2021-08-07'
scandate = '2021-08-06'
min_avgVol_30d = '140000'
orderBy = 'vwap'

In [4]:
scanql = ( 
    '''
    SELECT * FROM "{dbTable}"
    WHERE "date" LIKE '{scandate}'
    AND "avgVol_30d" > {min_avgVol_30d}
    ORDER BY "{orderBy}" DESC;
    '''
).format(dbTable=dbTable, scandate=scandate, min_avgVol_30d=min_avgVol_30d, orderBy=orderBy)

engine = ( 
    create_engine(
        'postgresql+psycopg2://postgres:s@unAsh*w3r@localhost/market'
    )
)
dbdf = pd.read_sql_query(sql=scanql, con=engine)

dbdf.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3620 entries, 0 to 3619
Columns: 220 entries, ticker to close_pctf_ATRonSMA10
dtypes: float64(215), int64(2), object(3)
memory usage: 6.5 MB

---
## | bop + close_24_sub_n_pctf_1wk_low

In [4]:
''' name : code 1'''

dbdf.loc[ 
    (
        dbdf['bop'].between(
            left=-0.0344827586206888,
            right=1.0
        )
    ) & ( 
        dbdf['close_24_sub_n_pctf_1wk_low'].between( 
            left=-3.6352244246981,
            right=-0.989618477282944
        )
    ) & ( 
        dbdf['VIp_chngpct_24'].between( 
            left=0.248481069328843,
            right=66.0881285943027
        )
    ) & ( 
        dbdf['MACD_sub_nMACD_Sig_n_diff'].between( 
            left=-0.632410293660814,
            right=-0.0208748448896303
        )
    )
]

Empty DataFrame
Columns: [ticker, volume, vwap, open, close, high, low, timestamp, transactions, date, close_chngpct_24, close_chngpct_48, close_chngpct_72, close_chngpct_24_tmro, close_chngpct_24_yday, close_chngpct_48_yday, close_down3, perf_1wk, perf_1wk_sub_pchngpct_24, perf_1wk_sub_nchngpct_24, close_chngpct_1wk_high, close_24_sub_p_pctf_1wk_high, close_24_sub_n_pctf_1wk_high, close_chngpct_1wk_low, close_24_sub_p_pctf_1wk_low, close_24_sub_n_pctf_1wk_low, perf_1mo, close_chngpct_1mo_high, close_chngpct_1mo_low, vwap_chngpct_24, vwap_chngpct_48, vwap_chngpct_72, vwap_chngpct_24_yday, vwap_chngpct_48_yday, volume_chngpct_24, volume_1wk_high, volume_1wk_low, volume_chngpct_vhigh, volume_chngpct_vlow, close_at_vhigh_1wk, close_at_vlow_1wk, close_pctf_vhigh_1wk, close_pctf_vlow_1wk, avgVol_10d, rvol, avgVol_10d_chngpct_24, avgVol_10d_chngpct_48, avgVol_10d_chngpct_72, avgVol_30d, avgVol_30d_chngpct_24, avgVol_30d_chngpct_48, avgVol_30d_chngpct_72, avgVol_10d_pctf_av30d, volume_by_price, WOBV, WOBV_chngpct_24, WOBV_chngpct_48, WOBV_chngpct_72, EFI, EFI_diff_p_24, EFI_diff_n_24, gap, bop, bop_diff_p_24, bop_diff_n_24, bop_at_vhigh_1wk, bop_sub_p_vhigh_1wk, bop_sub_n_vhigh_1wk, bop_at_vlow_1wk, bop_sub_p_vlow_1wk, bop_sub_n_vlow_1wk, bop_SMA3, bop_EMA3, bop_week, bull_power, bear_power, bullPwr_diff_p_24, bullPwr_diff_n_24, bearPwr_diff_p_24, bearPwr_diff_n_24, bullPwr_sub_p_bearPwr, bullPwr_sub_n_bearPwr, normBP, normSP, normBP_chngpct_24, normBP_chngpct_48, normSP_chngpct_24, normSP_chngpct_48, normBP_pctf_normSP, normBP_div_normSP, normBP_div_normSP_chngpct_24, normBP_div_normSP_chngpct_48, MOM5, MOM10, MOM5_sub_p_MOM10, MOM5_sub_n_MOM10, VIm, VIp, VIp_chngpct_24, VIp_chngpct_48, ...]
Index: []

[0 rows x 220 columns]

In [5]:
''' name: code 2 '''

dbdf.loc[ 
        (
            dbdf['bop'].between(
                left=-0.0344827586206888,
                right=1.0
            )
        ) & ( 
            dbdf['close_24_sub_n_pctf_1wk_low'].between( 
                left=-3.6352244246981,
                right=-0.989618477282944
            )
        ) & ( 
            dbdf['VIp_chngpct_48'].between( 
                left=-1.12179978077341,
                right=50.834378169798
            )
        ) & ( 
            dbdf['EFI_diff_n_24'].between( 
                left=-10122471.3945867,
                right=-15114.5246037209
            )
        )
]

,ticker,volume,vwap,open,close,high,low,timestamp,transactions,date,...,close_pctf_SMA50,SMA10_pctf_SMA50,SMA100,close_pctf_SMA100,SMA10_pctf_SMA100,SMA50_pctf_SMA100,SMA10_plus_TR,close_pctf_TRonSMA10,SMA10_plus_ATR,close_pctf_ATRonSMA10
1615,HEAR,602321.0,28.0187,28.4008,28.40,28.8999,26.91,1628280000000,7054.0,2021-08-06,...,-11.260538,-6.301752,29.8654,-11.260538,0.407160,7.160125,31.987,-11.213931,31.328993,-9.349145
2237,LGF.A,948291.0,14.2406,14.1200,14.23,14.5350,13.50,1628280000000,10843.0,2021-08-06,...,-23.154188,-19.238994,17.3271,-23.154188,-13.690115,6.870740,16.165,-11.970306,15.676779,-9.228800
2307,AG,3121333.0,12.9965,12.8300,13.08,13.1950,12.71,1628280000000,17610.0,2021-08-06,...,-15.046179,-13.760181,15.8914,-15.046179,-16.445373,-3.113634,13.868,-5.682146,13.806214,-5.260054
2872,HL,6371885.0,6.1286,6.0000,6.20,6.2300,5.98,1628280000000,25508.0,2021-08-06,...,-18.739679,-14.807728,7.1679,-18.739679,-9.317931,6.444007,6.860,-9.620991,6.822486,-9.124031

In [6]:
''' name: code 3 '''

dbdf.loc[ 
        (
            dbdf['bop'].between(
                left=-0.0344827586206888,
                right=1.0
            )
        ) & ( 
            dbdf['close_24_sub_n_pctf_1wk_low'].between( 
                left=-3.6352244246981,
                right=-0.989618477282944
            )
        ) & ( 
            dbdf['VIp_div_VIm_chngpct_24'].between( 
                left=-1.31233880869641,
                right=71.0154728635913
            )
        ) & ( 
            dbdf['WOBV_chngpct_24'].between( 
                left=-11122.4058683351,
                right=-0.785865762803328
            )
        )
]

,ticker,volume,vwap,open,close,high,low,timestamp,transactions,date,...,close_pctf_SMA50,SMA10_pctf_SMA50,SMA100,close_pctf_SMA100,SMA10_pctf_SMA100,SMA50_pctf_SMA100,SMA10_plus_TR,close_pctf_TRonSMA10,SMA10_plus_ATR,close_pctf_ATRonSMA10
2278,GATO,875963.0,13.4494,13.5,13.5,13.70,12.84,1628280000000,6846.0,2021-08-06,...,-17.551210,-16.873298,14.1901,-17.551210,-4.081014,15.388898,14.471,-6.709972,14.379093,-6.113688
2872,HL,6371885.0,6.1286,6.0,6.2,6.23,5.98,1628280000000,25508.0,2021-08-06,...,-18.739679,-14.807728,7.1679,-18.739679,-9.317931,6.444007,6.860,-9.620991,6.822486,-9.124031

In [7]:
''' name : code 4 '''

dbdf.loc[ 
        (
            dbdf['bop'].between(
                left=-0.0344827586206888,
                right=1.0
            )
        ) & ( 
            dbdf['close_24_sub_n_pctf_1wk_low'].between( 
                left=-3.6352244246981,
                right=-0.989618477282944
            )
        ) & ( 
            dbdf['bullPwr_diff_n_24'].between( 
                left=-12.2702620028771,
                right=-0.255283014371189
            )
        ) & ( 
            dbdf['perf_1mo'].between( 
                left=-13.8451911347686,
                right=-1.92526521899627
            )
        )
]

Empty DataFrame
Columns: [ticker, volume, vwap, open, close, high, low, timestamp, transactions, date, close_chngpct_24, close_chngpct_48, close_chngpct_72, close_chngpct_24_tmro, close_chngpct_24_yday, close_chngpct_48_yday, close_down3, perf_1wk, perf_1wk_sub_pchngpct_24, perf_1wk_sub_nchngpct_24, close_chngpct_1wk_high, close_24_sub_p_pctf_1wk_high, close_24_sub_n_pctf_1wk_high, close_chngpct_1wk_low, close_24_sub_p_pctf_1wk_low, close_24_sub_n_pctf_1wk_low, perf_1mo, close_chngpct_1mo_high, close_chngpct_1mo_low, vwap_chngpct_24, vwap_chngpct_48, vwap_chngpct_72, vwap_chngpct_24_yday, vwap_chngpct_48_yday, volume_chngpct_24, volume_1wk_high, volume_1wk_low, volume_chngpct_vhigh, volume_chngpct_vlow, close_at_vhigh_1wk, close_at_vlow_1wk, close_pctf_vhigh_1wk, close_pctf_vlow_1wk, avgVol_10d, rvol, avgVol_10d_chngpct_24, avgVol_10d_chngpct_48, avgVol_10d_chngpct_72, avgVol_30d, avgVol_30d_chngpct_24, avgVol_30d_chngpct_48, avgVol_30d_chngpct_72, avgVol_10d_pctf_av30d, volume_by_price, WOBV, WOBV_chngpct_24, WOBV_chngpct_48, WOBV_chngpct_72, EFI, EFI_diff_p_24, EFI_diff_n_24, gap, bop, bop_diff_p_24, bop_diff_n_24, bop_at_vhigh_1wk, bop_sub_p_vhigh_1wk, bop_sub_n_vhigh_1wk, bop_at_vlow_1wk, bop_sub_p_vlow_1wk, bop_sub_n_vlow_1wk, bop_SMA3, bop_EMA3, bop_week, bull_power, bear_power, bullPwr_diff_p_24, bullPwr_diff_n_24, bearPwr_diff_p_24, bearPwr_diff_n_24, bullPwr_sub_p_bearPwr, bullPwr_sub_n_bearPwr, normBP, normSP, normBP_chngpct_24, normBP_chngpct_48, normSP_chngpct_24, normSP_chngpct_48, normBP_pctf_normSP, normBP_div_normSP, normBP_div_normSP_chngpct_24, normBP_div_normSP_chngpct_48, MOM5, MOM10, MOM5_sub_p_MOM10, MOM5_sub_n_MOM10, VIm, VIp, VIp_chngpct_24, VIp_chngpct_48, ...]
Index: []

[0 rows x 220 columns]

---
## | bop_diff_n_24 + RSI7_div_RSI14_chngpct_24

In [8]:
''' name : code 5 '''

dbdf.loc[ 
        (
            dbdf['bop_diff_n_24'].between(
                left= 0.847660246274722,
                right= 2.0
            )
        ) & ( 
            dbdf['RSI7_div_RSI14_chngpct_24'].between( 
                left= -73.4032707603346,
                right= -0.972687810693496
            )
        ) & ( 
            dbdf['pctK_div_pctD_chngpct_24'].between( 
                left= 262.263214486447,
                right= 273387.705557057
            )
        ) & ( 
            dbdf['VIp_div_VIm_chngpct_48'].between( 
                left= -14.7396795530375,
                right= 314.208341638019
            )
        )
]

Empty DataFrame
Columns: [ticker, volume, vwap, open, close, high, low, timestamp, transactions, date, close_chngpct_24, close_chngpct_48, close_chngpct_72, close_chngpct_24_tmro, close_chngpct_24_yday, close_chngpct_48_yday, close_down3, perf_1wk, perf_1wk_sub_pchngpct_24, perf_1wk_sub_nchngpct_24, close_chngpct_1wk_high, close_24_sub_p_pctf_1wk_high, close_24_sub_n_pctf_1wk_high, close_chngpct_1wk_low, close_24_sub_p_pctf_1wk_low, close_24_sub_n_pctf_1wk_low, perf_1mo, close_chngpct_1mo_high, close_chngpct_1mo_low, vwap_chngpct_24, vwap_chngpct_48, vwap_chngpct_72, vwap_chngpct_24_yday, vwap_chngpct_48_yday, volume_chngpct_24, volume_1wk_high, volume_1wk_low, volume_chngpct_vhigh, volume_chngpct_vlow, close_at_vhigh_1wk, close_at_vlow_1wk, close_pctf_vhigh_1wk, close_pctf_vlow_1wk, avgVol_10d, rvol, avgVol_10d_chngpct_24, avgVol_10d_chngpct_48, avgVol_10d_chngpct_72, avgVol_30d, avgVol_30d_chngpct_24, avgVol_30d_chngpct_48, avgVol_30d_chngpct_72, avgVol_10d_pctf_av30d, volume_by_price, WOBV, WOBV_chngpct_24, WOBV_chngpct_48, WOBV_chngpct_72, EFI, EFI_diff_p_24, EFI_diff_n_24, gap, bop, bop_diff_p_24, bop_diff_n_24, bop_at_vhigh_1wk, bop_sub_p_vhigh_1wk, bop_sub_n_vhigh_1wk, bop_at_vlow_1wk, bop_sub_p_vlow_1wk, bop_sub_n_vlow_1wk, bop_SMA3, bop_EMA3, bop_week, bull_power, bear_power, bullPwr_diff_p_24, bullPwr_diff_n_24, bearPwr_diff_p_24, bearPwr_diff_n_24, bullPwr_sub_p_bearPwr, bullPwr_sub_n_bearPwr, normBP, normSP, normBP_chngpct_24, normBP_chngpct_48, normSP_chngpct_24, normSP_chngpct_48, normBP_pctf_normSP, normBP_div_normSP, normBP_div_normSP_chngpct_24, normBP_div_normSP_chngpct_48, MOM5, MOM10, MOM5_sub_p_MOM10, MOM5_sub_n_MOM10, VIm, VIp, VIp_chngpct_24, VIp_chngpct_48, ...]
Index: []

[0 rows x 220 columns]

In [9]:
''' code: 6 '''

dbdf.loc[ 
        (
            dbdf['bop_diff_n_24'].between(
                left= 0.847660246274722,
                right= 2.0
            )
        ) & ( 
            dbdf['RSI7_div_RSI14_chngpct_24'].between( 
                left= -73.4032707603346,
                right= -0.972687810693496
            )
        ) & ( 
            dbdf['pctK_chngpct_24'].between( 
                left= 246.666666666656,
                right= 2552548.37268666
            )
        ) & ( 
            dbdf['RSI7_chngpct_24'].between( 
                left= -79.3594038192463,
                right= -7.84150793487602
            )
        )
]

Empty DataFrame
Columns: [ticker, volume, vwap, open, close, high, low, timestamp, transactions, date, close_chngpct_24, close_chngpct_48, close_chngpct_72, close_chngpct_24_tmro, close_chngpct_24_yday, close_chngpct_48_yday, close_down3, perf_1wk, perf_1wk_sub_pchngpct_24, perf_1wk_sub_nchngpct_24, close_chngpct_1wk_high, close_24_sub_p_pctf_1wk_high, close_24_sub_n_pctf_1wk_high, close_chngpct_1wk_low, close_24_sub_p_pctf_1wk_low, close_24_sub_n_pctf_1wk_low, perf_1mo, close_chngpct_1mo_high, close_chngpct_1mo_low, vwap_chngpct_24, vwap_chngpct_48, vwap_chngpct_72, vwap_chngpct_24_yday, vwap_chngpct_48_yday, volume_chngpct_24, volume_1wk_high, volume_1wk_low, volume_chngpct_vhigh, volume_chngpct_vlow, close_at_vhigh_1wk, close_at_vlow_1wk, close_pctf_vhigh_1wk, close_pctf_vlow_1wk, avgVol_10d, rvol, avgVol_10d_chngpct_24, avgVol_10d_chngpct_48, avgVol_10d_chngpct_72, avgVol_30d, avgVol_30d_chngpct_24, avgVol_30d_chngpct_48, avgVol_30d_chngpct_72, avgVol_10d_pctf_av30d, volume_by_price, WOBV, WOBV_chngpct_24, WOBV_chngpct_48, WOBV_chngpct_72, EFI, EFI_diff_p_24, EFI_diff_n_24, gap, bop, bop_diff_p_24, bop_diff_n_24, bop_at_vhigh_1wk, bop_sub_p_vhigh_1wk, bop_sub_n_vhigh_1wk, bop_at_vlow_1wk, bop_sub_p_vlow_1wk, bop_sub_n_vlow_1wk, bop_SMA3, bop_EMA3, bop_week, bull_power, bear_power, bullPwr_diff_p_24, bullPwr_diff_n_24, bearPwr_diff_p_24, bearPwr_diff_n_24, bullPwr_sub_p_bearPwr, bullPwr_sub_n_bearPwr, normBP, normSP, normBP_chngpct_24, normBP_chngpct_48, normSP_chngpct_24, normSP_chngpct_48, normBP_pctf_normSP, normBP_div_normSP, normBP_div_normSP_chngpct_24, normBP_div_normSP_chngpct_48, MOM5, MOM10, MOM5_sub_p_MOM10, MOM5_sub_n_MOM10, VIm, VIp, VIp_chngpct_24, VIp_chngpct_48, ...]
Index: []

[0 rows x 220 columns]

In [10]:
''' code: 7 '''
''' 366 / 398 | 0.920 (july 6 - august 6) '''

dbdf.loc[ 
        (
            dbdf['bop_diff_n_24'].between(
                left= 0.847660246274722,
                right= 2.0
            )
        ) & ( 
            dbdf['RSI7_div_RSI14_chngpct_24'].between( 
                left= -73.4032707603346,
                right= -0.972687810693496
            )
        ) & ( 
            dbdf['MOM5'].between( 
                left= -168.96,
                right= -1.13
            )
        ) & ( 
            dbdf['RSI7_chngpct_24'].between( 
                left= -79.3594038192463,
                right= -7.84150793487602
            )
        )
]

,ticker,volume,vwap,open,close,high,low,timestamp,transactions,date,...,close_pctf_SMA50,SMA10_pctf_SMA50,SMA100,close_pctf_SMA100,SMA10_pctf_SMA100,SMA50_pctf_SMA100,SMA10_plus_TR,close_pctf_TRonSMA10,SMA10_plus_ATR,close_pctf_ATRonSMA10
450,RGLD,325989.0,115.7769,115.39,116.06,116.51,114.11,1628280000000,7816.0,2021-08-06,...,-1.400075,0.630373,116.1990,-1.400075,1.937194,1.298634,121.170,-4.217215,120.827857,-3.945992
592,LOPE,385304.0,89.9992,88.83,89.55,91.66,88.83,1628280000000,6930.0,2021-08-06,...,-1.277059,0.762443,98.1707,-1.277059,-6.896864,-7.601352,94.230,-4.966571,93.697429,-4.426406
909,AEM,1270547.0,60.3854,60.30,60.53,60.89,59.70,1628280000000,15758.0,2021-08-06,...,-6.318002,-3.652871,64.5004,-6.318002,-3.485870,0.173332,64.382,-5.983039,63.954071,-5.353954

---
## | RSI7_chngpct_24 + bop_sub_p_vhigh_1wk

In [5]:
''' code: 8 '''
''' 102 / 113 | 0.903 (july 6 - august 6) '''

dbdf.loc[ 
        (
            dbdf['RSI7_chngpct_24'].between(
                left= -94.8258405816019,
                right= -1.7799533681546
            )
        ) & ( 
            dbdf['bop_sub_p_vhigh_1wk'].between( 
                left= -0.298095691865992,
                right= 0.975308641975314
            )
        ) & ( 
            dbdf['pctD_chngpct_24'].between( 
                left= 10.1916324817648,
                right= 199.135908730818
            )
        ) & ( 
            dbdf['pctD_chngpct_48'].between( 
                left= -87.3431911850693,
                right= -7.63687242651038
            )
        )
]

Empty DataFrame
Columns: [ticker, volume, vwap, open, close, high, low, timestamp, transactions, date, close_chngpct_24, close_chngpct_48, close_chngpct_72, close_chngpct_24_tmro, close_chngpct_24_yday, close_chngpct_48_yday, close_down3, perf_1wk, perf_1wk_sub_pchngpct_24, perf_1wk_sub_nchngpct_24, close_chngpct_1wk_high, close_24_sub_p_pctf_1wk_high, close_24_sub_n_pctf_1wk_high, close_chngpct_1wk_low, close_24_sub_p_pctf_1wk_low, close_24_sub_n_pctf_1wk_low, perf_1mo, close_chngpct_1mo_high, close_chngpct_1mo_low, vwap_chngpct_24, vwap_chngpct_48, vwap_chngpct_72, vwap_chngpct_24_yday, vwap_chngpct_48_yday, volume_chngpct_24, volume_1wk_high, volume_1wk_low, volume_chngpct_vhigh, volume_chngpct_vlow, close_at_vhigh_1wk, close_at_vlow_1wk, close_pctf_vhigh_1wk, close_pctf_vlow_1wk, avgVol_10d, rvol, avgVol_10d_chngpct_24, avgVol_10d_chngpct_48, avgVol_10d_chngpct_72, avgVol_30d, avgVol_30d_chngpct_24, avgVol_30d_chngpct_48, avgVol_30d_chngpct_72, avgVol_10d_pctf_av30d, volume_by_price, WOBV, WOBV_chngpct_24, WOBV_chngpct_48, WOBV_chngpct_72, EFI, EFI_diff_p_24, EFI_diff_n_24, gap, bop, bop_diff_p_24, bop_diff_n_24, bop_at_vhigh_1wk, bop_sub_p_vhigh_1wk, bop_sub_n_vhigh_1wk, bop_at_vlow_1wk, bop_sub_p_vlow_1wk, bop_sub_n_vlow_1wk, bop_SMA3, bop_EMA3, bop_week, bull_power, bear_power, bullPwr_diff_p_24, bullPwr_diff_n_24, bearPwr_diff_p_24, bearPwr_diff_n_24, bullPwr_sub_p_bearPwr, bullPwr_sub_n_bearPwr, normBP, normSP, normBP_chngpct_24, normBP_chngpct_48, normSP_chngpct_24, normSP_chngpct_48, normBP_pctf_normSP, normBP_div_normSP, normBP_div_normSP_chngpct_24, normBP_div_normSP_chngpct_48, MOM5, MOM10, MOM5_sub_p_MOM10, MOM5_sub_n_MOM10, VIm, VIp, VIp_chngpct_24, VIp_chngpct_48, ...]
Index: []

[0 rows x 220 columns]

In [6]:
''' code: 9 '''
''' 250 / 283 | 0.883 (july 6 - august 6) '''

dbdf.loc[ 
        (
            dbdf['RSI7_chngpct_24'].between(
                left= -94.8258405816019,
                right= -1.7799533681546
            )
        ) & ( 
            dbdf['bop_sub_p_vhigh_1wk'].between( 
                left= -0.298095691865992,
                right= 0.975308641975314
            )
        ) & ( 
            dbdf['pctK_chngpct_24'].between( 
                left= 3.84726827854829,
                right= 1891791.89189189
            )
        ) & ( 
            dbdf['EFI_diff_n_24'].between( 
                left= -32523874.3241804,
                right= -8609.22274980179
            )
        )
]

,ticker,volume,vwap,open,close,high,low,timestamp,transactions,date,...,close_pctf_SMA50,SMA10_pctf_SMA50,SMA100,close_pctf_SMA100,SMA10_pctf_SMA100,SMA50_pctf_SMA100,SMA10_plus_TR,close_pctf_TRonSMA10,SMA10_plus_ATR,close_pctf_ATRonSMA10
1376,COLD,10450336.0,36.7702,35.25,37.21,37.400,34.84,1628280000000,54920.0,2021-08-06,...,-3.917660,-0.439484,38.6527,-3.917660,-0.247589,0.192742,42.447,-12.337739,39.593636,-6.02025
2237,LGF.A,948291.0,14.2406,14.12,14.23,14.535,13.50,1628280000000,10843.0,2021-08-06,...,-23.154188,-19.238994,17.3271,-23.154188,-13.690115,6.870740,16.165,-11.970306,15.676779,-9.22880

---

In [ ]:
dbdf.sort_values(by='volume', ascending=False, inplace=True)
dbdf[['ticker', 'open', 'high', 'low', 'close', 'vwap', 'volume']].loc[lookup_idx].iloc[:50]

---
# | backscans

In [ ]:
dbTable = 'gd_wTi_2021-08-07'

stDate = '2021-07-06'
endDate = '2021-08-06'

min_avgVol_30d = '140000'

orderBy = 'close_chngpct_24_tmro'

In [ ]:
scanql = ( 
    '''
    SELECT * FROM "{dbTable}"
    WHERE "date" BETWEEN '{stDate}' AND '{endDate}'
    AND "avgVol_30d" > {min_avgVol_30d}
    ORDER BY "{orderBy}";
    '''
).format(dbTable=dbTable, stDate=stDate, endDate=endDate, min_avgVol_30d=min_avgVol_30d, orderBy=orderBy)


engine = ( 
    create_engine(
        'postgresql+psycopg2://postgres:s@unAsh*w3r@localhost/market'
    )
)
dbdf = pd.read_sql_query(sql=scanql, con=engine)

dbdf.drop(index=dbdf.loc[dbdf['close_chngpct_24_tmro'].isnull()].index, inplace=True)
dbdf.sort_values(by='close_chngpct_24_tmro', ascending=False, ignore_index=True, inplace=True)

dbdf.info(memory_usage='deep')

---

In [ ]:
''' 103 / 103 | 100% (july 6 - august 6) '''

len(
    dbdf.loc[ 
        (
            dbdf['bop'].between(
                left=-0.0344827586206888,
                right=1.0
            )
        ) & ( 
            dbdf['close_24_sub_n_pctf_1wk_low'].between( 
                left=-3.6352244246981,
                right=-0.989618477282944
            )
        ) & ( 
            dbdf['VIp_chngpct_24'].between( 
                left=0.248481069328843,
                right=66.0881285943027
            )
        ) & ( 
            dbdf['MACD_sub_nMACD_Sig_n_diff'].between( 
                left=-0.632410293660814,
                right=-0.0208748448896303
            )
        )
    ]
)

In [ ]:
len(
    dbdf.loc[ 
        (
            dbdf['bop'].between(
                left=-0.0344827586206888,
                right=1.0
            )
        ) & ( 
            dbdf['close_24_sub_n_pctf_1wk_low'].between( 
                left=-3.6352244246981,
                right=-0.989618477282944
            )
        ) & ( 
            dbdf['VIp_chngpct_24'].between( 
                left=0.248481069328843,
                right=66.0881285943027
            )
        ) & ( 
            dbdf['MACD_sub_nMACD_Sig_n_diff'].between( 
                left=-0.632410293660814,
                right=-0.0208748448896303
            )
        ) & ( 
            dbdf['close_chngpct_24_tmro'] > 0
        )
    ]
)

---

In [ ]:
''' 128 / 131 | 0.977 (july 6 - august 6) '''
len(
    dbdf.loc[ 
        (
            dbdf['bop'].between(
                left=-0.0344827586206888,
                right=1.0
            )
        ) & ( 
            dbdf['close_24_sub_n_pctf_1wk_low'].between( 
                left=-3.6352244246981,
                right=-0.989618477282944
            )
        ) & ( 
            dbdf['VIp_chngpct_48'].between( 
                left=-1.12179978077341,
                right=50.834378169798
            )
        ) & ( 
            dbdf['EFI_diff_n_24'].between( 
                left=-10122471.3945867,
                right=-15114.5246037209
            )
        ) & ( 
            dbdf['close_chngpct_24_tmro'] > 0
        )
    ]
)

In [ ]:
''' 215 / 221 | 0.977 (july 6 - august 6) '''
len(
    dbdf.loc[ 
        (
            dbdf['bop'].between(
                left=-0.0344827586206888,
                right=1.0
            )
        ) & ( 
            dbdf['close_24_sub_n_pctf_1wk_low'].between( 
                left=-3.6352244246981,
                right=-0.989618477282944
            )
        ) & ( 
            dbdf['VIp_div_VIm_chngpct_24'].between( 
                left=-1.31233880869641,
                right=71.0154728635913
            )
        ) & ( 
            dbdf['WOBV_chngpct_24'].between( 
                left=-11122.4058683351,
                right=-0.785865762803328
            )
        ) & ( 
            dbdf['close_chngpct_24_tmro'] > 0
        )
    ]
)

In [ ]:
''' 332 / 349 | 0.951 (july 6 - august 6) '''
len(
    dbdf.loc[ 
        (
            dbdf['bop'].between(
                left=-0.0344827586206888,
                right=1.0
            )
        ) & ( 
            dbdf['close_24_sub_n_pctf_1wk_low'].between( 
                left=-3.6352244246981,
                right=-0.989618477282944
            )
        ) & ( 
            dbdf['bullPwr_diff_n_24'].between( 
                left=-12.2702620028771,
                right=-0.255283014371189
            )
        ) & ( 
            dbdf['perf_1mo'].between( 
                left=-13.8451911347686,
                right=-1.92526521899627
            )
        ) & ( 
            dbdf['close_chngpct_24_tmro'] > 0
        )
    ]
)

---

In [ ]:
len( 
    dbdf.loc[ 
        (
            dbdf['bop_diff_n_24'].between(
                left=0.847660246274722,
                right=2.0
            )
        ) & ( 
            dbdf['close_24_sub_n_pctf_1wk_low'].between( 
                left=-3.6352244246981,
                right=-0.989618477282944
            )
        ) & ( dbdf['close_chngpct_24_tmro'] > 0)
    ]
)

In [ ]:
pandascan.bop__normBP_chngpct_24__close_24_sub_n_pctf_1wk_low(df=dbdf)

In [ ]:
pandascan.blip_array

In [ ]:
blip_df = pandascan.return_blip_df()
blip_df

In [ ]:
lookup_idx = blip_df.loc[
    blip_df['filters'] == 'bop_volume_vwap_close_24_sub_n_pctf_1wk_low'
]['blips_idx'][0]

In [ ]:
pandascan.Ov0c_of( 
    df=dbdf,
    Ov0_cutoff=0,
    test_idx=lookup_idx,
    test_name='bop__close_24_sub_n_pctf_1wk_low'
)

In [ ]:
dbdf.loc[lookup_idx]

---
## | subset

In [ ]:
pandascan.bop__vwap__pctK_div_pctD_chngpct_48__close_24_sub_n_pctf_1wk_low( 
    df=(
        dbdf.loc[
            dbdf['date'].between( 
                left='2021-07-01',
                right='2021-08-07'
            )
        ]
    )
)

In [ ]:
blip_df = pandascan.return_blip_df()
blip_df

In [ ]:
blip_df.at[1, 'blips_idx']

In [ ]:
pandascan.Ov0c_of(
    df=(
        dbdf.loc[
            dbdf['date'].between( 
                left='2021-07-01',
                right='2021-08-07'
            )
        ]
    ),
    Ov0_cutoff=0,
    test_idx=( 
        blip_df.at[1, 'blips_idx']
    ),
    test_name='july_bop_volume_vwap_close_24_sub_n_pctf_1wk_low'
)